Add user controller test
bounswe/bounswe2017group3 pull request #87
Opened 2017-05-07 12:45 UTC by gokceuludogan

## About

* **Other Related Links:** https://blog.jayway.com/2014/07/04/integration-testing-a-spring-boot-application/

Since we should create unit tests for our API, I have created some unit tests of UserController using Rest Assured Mock Mvc library.   

### Changes

- Added constructors to User
- Added test class for UserController.
- Tested some endpoints:
  - `GET /user`
  - `DELETE /user`
  - `GET /user?username=' '`

2017-05-07 20:51 UTC, smddzcy commented on events-application-rest-api/src/main/java/com/bounswe/bounswe2017group3/Model/User.java
> +    @Temporal(javax.persistence.TemporalType.DATE)
👍

2017-05-07 20:57 UTC, smddzcy requested changes
Everything looks perfect, thanks👌  Just some minor changes and then we can deploy it 🚀

2017-05-07 20:57 UTC, smddzcy commented on events-application-rest-api/src/test/java/com/bounswe/bounswe2017group3/Model/UserControllerTest.java
> +    public void canGetByUsername() {
Maybe we can include a short comment to describe what this function tests.

2017-05-07 20:57 UTC, smddzcy commented on events-application-rest-api/src/main/java/com/bounswe/bounswe2017group3/Model/User.java
> +    public User(){
We can make it like `public User(){}` since the method body is empty 😄  I suggest to run an autoformat with your IDE, it should be sufficient.

2017-05-07 20:57 UTC, smddzcy commented on events-application-rest-api/src/test/java/com/bounswe/bounswe2017group3/Model/UserControllerTest.java
> +        repository.deleteAll();
This is a mocked repository and doesn't delete our _actual_ records, right? 😅  I don't have any experience with RestAssured or testing Spring applications, so I'm just asking to be sure.

2017-05-07 22:37 UTC, gokceuludogan commented on events-application-rest-api/src/main/java/com/bounswe/bounswe2017group3/Model/User.java
> +    public User(){
Ok I have fixed it :smile:

2017-05-07 22:39 UTC, gokceuludogan commented on events-application-rest-api/src/test/java/com/bounswe/bounswe2017group3/Model/UserControllerTest.java
> +        repository.deleteAll();
You are right :smile: I didn't realize that it deletes our actual repository :smile: So, I have changed it with the one using Mocks

2017-05-07 22:41 UTC, gokceuludogan commented
Since the old one is lacking from mocks and using actual repository, I have changed the class and the test with Mocks:smile:

2017-05-08 11:57 UTC, smddzcy commented on events-application-rest-api/src/test/java/com/bounswe/bounswe2017group3/Model/UserControllerTest.java
> +        verifyNoMoreInteractions(repo);
Perfect 👌

2017-05-08 11:57 UTC, smddzcy approved these changes

2017-05-08 12:08 UTC, merged